-- =============================================================================
-- InTrainin — 006_full_catalog.sql
-- Complete role catalog: fixes slug mismatches, aligns category names,
-- adds all 15 roles with full module structure + placeholder topics.
--
-- WHAT THIS FIXES vs 004_seed.sql:
--   • 'cashier'        → 'cashier-retail'   (matches lib/roles.ts routing)
--   • 'delivery-rider' → 'dispatch-rider'   (matches lib/roles.ts routing)
--   • category 'Retail' → 'Retail & Store Ops'
--   • category 'Cleaning & Facilities' → 'Sales & Marketing'
--   • 3 → 15 roles   (adds store-attendant, barista, customer-service-rep,
--     receptionist, hairdresser, security-guard, cook-kitchen-hand, sales-rep,
--     hotel-housekeeper, barber, front-desk-agent, warehouse-picker)
--   • Adds missing modules 3-5 for cashier, waiter-waitress, modules 3-4 for
--     dispatch-rider, then full module sets for the 12 new roles.
--   • DO block generates placeholder topics for every new module (idempotent).
--
-- IDEMPOTENT: all INSERTs use ON CONFLICT DO NOTHING; UPDATEs are safe to
--   rerun. The DO block uses WHERE NOT EXISTS guards.
--
-- UUID CONVENTIONS (deterministic, no random UUIDs in seed data):
--   Categories:  a000000{n}-0000-0000-0000-000000000000  (1-7)
--   Roles:       b000000{n}-0000-0000-0000-000000000000  (1-15 / 0f in hex)
--   Modules:     c000000{n}-0000-0000-0000-000000000000  (1-46 in hex)
--   Topics:      generated by DO block (placeholder, replaced by Sanity later)
-- =============================================================================


-- =============================================================================
-- 1. FIX CATEGORY NAMES  (align with lib/roles.ts display strings)
-- =============================================================================

UPDATE categories SET name = 'Retail & Store Ops', slug = 'retail-store-ops'
  WHERE id = 'a0000001-0000-0000-0000-000000000000';

UPDATE categories SET name = 'Sales & Marketing', slug = 'sales-marketing'
  WHERE id = 'a0000007-0000-0000-0000-000000000000';


-- =============================================================================
-- 2. FIX ROLE SLUGS  (must match Next.js route params in lib/roles.ts)
-- =============================================================================

UPDATE roles SET slug = 'cashier-retail'
  WHERE id = 'b0000001-0000-0000-0000-000000000000';

UPDATE roles SET slug = 'dispatch-rider'
  WHERE id = 'b0000003-0000-0000-0000-000000000000';


-- =============================================================================
-- 3. ADD 12 NEW ROLES
-- =============================================================================

INSERT INTO roles (id, category_id, title, slug, description, price_ngn,
                   estimated_hours, is_published, free_preview_module_count, phase)
VALUES

  -- store-attendant (Retail & Store Ops)
  ('b0000004-0000-0000-0000-000000000000',
   'a0000001-0000-0000-0000-000000000000',
   'Store Attendant', 'store-attendant',
   'Stock management, customer handling, display standards, and security protocols.',
   2500, 3.5, true, 1, 1),

  -- barista (Food & Beverage)
  ('b0000005-0000-0000-0000-000000000000',
   'a0000002-0000-0000-0000-000000000000',
   'Barista', 'barista',
   'Espresso techniques, milk frothing, beverage recipes, hygiene, and equipment care.',
   2500, 4.0, true, 1, 1),

  -- customer-service-rep (Sales & Marketing)
  ('b0000006-0000-0000-0000-000000000000',
   'a0000007-0000-0000-0000-000000000000',
   'Customer Service Rep', 'customer-service-rep',
   'Complaint handling, communication, product knowledge, CRM basics, and follow-up.',
   2500, 4.0, true, 1, 1),

  -- receptionist (Admin & Office)
  ('b0000007-0000-0000-0000-000000000000',
   'a0000006-0000-0000-0000-000000000000',
   'Receptionist', 'receptionist',
   'Front desk operations, scheduling, communication etiquette, and office software basics.',
   2500, 4.0, true, 1, 1),

  -- hairdresser (Beauty & Wellness)
  ('b0000008-0000-0000-0000-000000000000',
   'a0000005-0000-0000-0000-000000000000',
   'Hairdresser', 'hairdresser',
   'Haircut techniques, client consultation, chemical treatments, and salon hygiene.',
   2500, 4.5, true, 1, 1),

  -- security-guard (Admin & Office)
  ('b0000009-0000-0000-0000-000000000000',
   'a0000006-0000-0000-0000-000000000000',
   'Security Guard', 'security-guard',
   'Access control, emergency response, report writing, and legal boundaries of duty.',
   2500, 3.5, true, 1, 1),

  -- cook-kitchen-hand (Food & Beverage)
  ('b000000a-0000-0000-0000-000000000000',
   'a0000002-0000-0000-0000-000000000000',
   'Cook / Kitchen Hand', 'cook-kitchen-hand',
   'Food preparation, kitchen hygiene, portion control, equipment safety, and shift coordination.',
   2500, 4.0, true, 1, 1),

  -- sales-rep (Sales & Marketing)
  ('b000000b-0000-0000-0000-000000000000',
   'a0000007-0000-0000-0000-000000000000',
   'Sales Representative', 'sales-rep',
   'Prospecting, pitching, objection handling, closing techniques, and after-sales follow-up.',
   2500, 4.0, true, 1, 1),

  -- hotel-housekeeper (Hospitality)
  ('b000000c-0000-0000-0000-000000000000',
   'a0000003-0000-0000-0000-000000000000',
   'Hotel Housekeeper', 'hotel-housekeeper',
   'Room turnover procedures, linen management, guest interaction, and chemical safety.',
   2500, 3.5, true, 1, 1),

  -- barber (Beauty & Wellness)
  ('b000000d-0000-0000-0000-000000000000',
   'a0000005-0000-0000-0000-000000000000',
   'Barber', 'barber',
   'Haircut styles, fade techniques, client consultation, tool sterilisation, and shop operations.',
   2500, 4.0, true, 1, 1),

  -- front-desk-agent (Hospitality)
  ('b000000e-0000-0000-0000-000000000000',
   'a0000003-0000-0000-0000-000000000000',
   'Front Desk Agent', 'front-desk-agent',
   'Check-in/out procedures, reservation systems, guest complaints, and upselling room upgrades.',
   2500, 4.5, true, 1, 1),

  -- warehouse-picker (Logistics)
  ('b000000f-0000-0000-0000-000000000000',
   'a0000004-0000-0000-0000-000000000000',
   'Warehouse Picker', 'warehouse-picker',
   'Pick-and-pack workflows, inventory accuracy, safe lifting, and warehouse communication.',
   2500, 3.0, true, 1, 1)

ON CONFLICT (id) DO NOTHING;


-- =============================================================================
-- 4. ADD MISSING MODULES FOR EXISTING 3 ROLES  (they only had 2 each)
--    + FULL MODULE SETS for the 12 new roles
-- =============================================================================

INSERT INTO modules (id, role_id, title, order_index, is_published) VALUES

  -- ── cashier-retail (b0000001) — modules 3-5 ──────────────────────────────
  ('c0000007-0000-0000-0000-000000000000', 'b0000001-0000-0000-0000-000000000000', 'Cash Handling & Reconciliation',   3, true),
  ('c0000008-0000-0000-0000-000000000000', 'b0000001-0000-0000-0000-000000000000', 'Store Policy & Loss Prevention',    4, true),
  ('c0000009-0000-0000-0000-000000000000', 'b0000001-0000-0000-0000-000000000000', 'Shift Operations & Handover',       5, true),

  -- ── waiter-waitress (b0000002) — modules 3-5 ─────────────────────────────
  ('c000000a-0000-0000-0000-000000000000', 'b0000002-0000-0000-0000-000000000000', 'Food Safety & Personal Hygiene',    3, true),
  ('c000000b-0000-0000-0000-000000000000', 'b0000002-0000-0000-0000-000000000000', 'Guest Handling & Complaints',       4, true),
  ('c000000c-0000-0000-0000-000000000000', 'b0000002-0000-0000-0000-000000000000', 'Shift Open & Close Procedures',     5, true),

  -- ── dispatch-rider (b0000003) — modules 3-4 ──────────────────────────────
  ('c000000d-0000-0000-0000-000000000000', 'b0000003-0000-0000-0000-000000000000', 'Delivery SOPs & Documentation',     3, true),
  ('c000000e-0000-0000-0000-000000000000', 'b0000003-0000-0000-0000-000000000000', 'Customer Interaction & Dispute Handling', 4, true),

  -- ── store-attendant (b0000004) — 4 modules ───────────────────────────────
  ('c000000f-0000-0000-0000-000000000000', 'b0000004-0000-0000-0000-000000000000', 'Store Operations Overview',         1, true),
  ('c0000010-0000-0000-0000-000000000000', 'b0000004-0000-0000-0000-000000000000', 'Stock Receiving & Inventory',       2, true),
  ('c0000011-0000-0000-0000-000000000000', 'b0000004-0000-0000-0000-000000000000', 'Shelf Display & Merchandising',     3, true),
  ('c0000012-0000-0000-0000-000000000000', 'b0000004-0000-0000-0000-000000000000', 'Customer Assistance & Sales',       4, true),

  -- ── barista (b0000005) — 5 modules ───────────────────────────────────────
  ('c0000013-0000-0000-0000-000000000000', 'b0000005-0000-0000-0000-000000000000', 'Coffee Fundamentals & Bean Knowledge',   1, true),
  ('c0000014-0000-0000-0000-000000000000', 'b0000005-0000-0000-0000-000000000000', 'Espresso Extraction Techniques',         2, true),
  ('c0000015-0000-0000-0000-000000000000', 'b0000005-0000-0000-0000-000000000000', 'Milk Steaming & Latte Art Basics',       3, true),
  ('c0000016-0000-0000-0000-000000000000', 'b0000005-0000-0000-0000-000000000000', 'Beverage Recipes & Menu Execution',      4, true),
  ('c0000017-0000-0000-0000-000000000000', 'b0000005-0000-0000-0000-000000000000', 'Equipment Care & Hygiene Compliance',    5, true),

  -- ── customer-service-rep (b0000006) — 5 modules ──────────────────────────
  ('c0000018-0000-0000-0000-000000000000', 'b0000006-0000-0000-0000-000000000000', 'Communication Skills for Customer Service', 1, true),
  ('c0000019-0000-0000-0000-000000000000', 'b0000006-0000-0000-0000-000000000000', 'Handling Complaints & Difficult Customers', 2, true),
  ('c000001a-0000-0000-0000-000000000000', 'b0000006-0000-0000-0000-000000000000', 'Product & Service Knowledge',              3, true),
  ('c000001b-0000-0000-0000-000000000000', 'b0000006-0000-0000-0000-000000000000', 'CRM Tools & Documentation',                4, true),
  ('c000001c-0000-0000-0000-000000000000', 'b0000006-0000-0000-0000-000000000000', 'Follow-up & Quality Standards',            5, true),

  -- ── receptionist (b0000007) — 5 modules ──────────────────────────────────
  ('c000001d-0000-0000-0000-000000000000', 'b0000007-0000-0000-0000-000000000000', 'Front Desk & Visitor Management',               1, true),
  ('c000001e-0000-0000-0000-000000000000', 'b0000007-0000-0000-0000-000000000000', 'Professional Communication & Phone Etiquette',  2, true),
  ('c000001f-0000-0000-0000-000000000000', 'b0000007-0000-0000-0000-000000000000', 'Scheduling & Calendar Management',              3, true),
  ('c0000020-0000-0000-0000-000000000000', 'b0000007-0000-0000-0000-000000000000', 'Office Software Basics',                        4, true),
  ('c0000021-0000-0000-0000-000000000000', 'b0000007-0000-0000-0000-000000000000', 'Record Keeping & Administrative Procedures',    5, true),

  -- ── hairdresser (b0000008) — 5 modules ───────────────────────────────────
  ('c0000022-0000-0000-0000-000000000000', 'b0000008-0000-0000-0000-000000000000', 'Salon Safety & Hygiene Standards',      1, true),
  ('c0000023-0000-0000-0000-000000000000', 'b0000008-0000-0000-0000-000000000000', 'Client Consultation & Hair Assessment',  2, true),
  ('c0000024-0000-0000-0000-000000000000', 'b0000008-0000-0000-0000-000000000000', 'Cutting & Styling Techniques',           3, true),
  ('c0000025-0000-0000-0000-000000000000', 'b0000008-0000-0000-0000-000000000000', 'Chemical Treatments & Colouring',        4, true),
  ('c0000026-0000-0000-0000-000000000000', 'b0000008-0000-0000-0000-000000000000', 'Product Knowledge & Client Retention',   5, true),

  -- ── security-guard (b0000009) — 4 modules ────────────────────────────────
  ('c0000027-0000-0000-0000-000000000000', 'b0000009-0000-0000-0000-000000000000', 'Security Guard Roles & Legal Responsibilities', 1, true),
  ('c0000028-0000-0000-0000-000000000000', 'b0000009-0000-0000-0000-000000000000', 'Access Control & Patrol Procedures',            2, true),
  ('c0000029-0000-0000-0000-000000000000', 'b0000009-0000-0000-0000-000000000000', 'Incident Reporting & Documentation',            3, true),
  ('c000002a-0000-0000-0000-000000000000', 'b0000009-0000-0000-0000-000000000000', 'Emergency Response Procedures',                 4, true),

  -- ── cook-kitchen-hand (b000000a) — 5 modules ─────────────────────────────
  ('c000002b-0000-0000-0000-000000000000', 'b000000a-0000-0000-0000-000000000000', 'Food Safety & Kitchen Hygiene (HACCP)',  1, true),
  ('c000002c-0000-0000-0000-000000000000', 'b000000a-0000-0000-0000-000000000000', 'Basic Cooking & Prep Techniques',        2, true),
  ('c000002d-0000-0000-0000-000000000000', 'b000000a-0000-0000-0000-000000000000', 'Equipment Operation & Safety',           3, true),
  ('c000002e-0000-0000-0000-000000000000', 'b000000a-0000-0000-0000-000000000000', 'Portion Control & Recipe Adherence',     4, true),
  ('c000002f-0000-0000-0000-000000000000', 'b000000a-0000-0000-0000-000000000000', 'Kitchen Teamwork & Shift Coordination',  5, true),

  -- ── sales-rep (b000000b) — 5 modules ─────────────────────────────────────
  ('c0000030-0000-0000-0000-000000000000', 'b000000b-0000-0000-0000-000000000000', 'Sales Mindset & Prospecting',              1, true),
  ('c0000031-0000-0000-0000-000000000000', 'b000000b-0000-0000-0000-000000000000', 'Building Rapport & Understanding Needs',   2, true),
  ('c0000032-0000-0000-0000-000000000000', 'b000000b-0000-0000-0000-000000000000', 'Pitching & Product Presentation',          3, true),
  ('c0000033-0000-0000-0000-000000000000', 'b000000b-0000-0000-0000-000000000000', 'Objection Handling',                       4, true),
  ('c0000034-0000-0000-0000-000000000000', 'b000000b-0000-0000-0000-000000000000', 'Closing & After-Sales Follow-up',          5, true),

  -- ── hotel-housekeeper (b000000c) — 4 modules ─────────────────────────────
  ('c0000035-0000-0000-0000-000000000000', 'b000000c-0000-0000-0000-000000000000', 'Housekeeping Standards & Guest Expectations', 1, true),
  ('c0000036-0000-0000-0000-000000000000', 'b000000c-0000-0000-0000-000000000000', 'Room Turnover Procedures',                    2, true),
  ('c0000037-0000-0000-0000-000000000000', 'b000000c-0000-0000-0000-000000000000', 'Linen & Amenity Management',                  3, true),
  ('c0000038-0000-0000-0000-000000000000', 'b000000c-0000-0000-0000-000000000000', 'Chemical Safety & Equipment Handling',        4, true),

  -- ── barber (b000000d) — 5 modules ────────────────────────────────────────
  ('c0000039-0000-0000-0000-000000000000', 'b000000d-0000-0000-0000-000000000000', 'Barbershop Hygiene & Tool Sterilisation', 1, true),
  ('c000003a-0000-0000-0000-000000000000', 'b000000d-0000-0000-0000-000000000000', 'Client Consultation & Haircut Planning',  2, true),
  ('c000003b-0000-0000-0000-000000000000', 'b000000d-0000-0000-0000-000000000000', 'Fade Techniques & Blending',              3, true),
  ('c000003c-0000-0000-0000-000000000000', 'b000000d-0000-0000-0000-000000000000', 'Lineups, Trims & Beard Styling',          4, true),
  ('c000003d-0000-0000-0000-000000000000', 'b000000d-0000-0000-0000-000000000000', 'Shop Operations & Client Retention',      5, true),

  -- ── front-desk-agent (b000000e) — 5 modules ──────────────────────────────
  ('c000003e-0000-0000-0000-000000000000', 'b000000e-0000-0000-0000-000000000000', 'Hotel Operations & Front Desk Role',         1, true),
  ('c000003f-0000-0000-0000-000000000000', 'b000000e-0000-0000-0000-000000000000', 'Check-in, Check-out & Reservations',         2, true),
  ('c0000040-0000-0000-0000-000000000000', 'b000000e-0000-0000-0000-000000000000', 'Property Management System (PMS) Basics',   3, true),
  ('c0000041-0000-0000-0000-000000000000', 'b000000e-0000-0000-0000-000000000000', 'Guest Relations & Complaint Handling',      4, true),
  ('c0000042-0000-0000-0000-000000000000', 'b000000e-0000-0000-0000-000000000000', 'Upselling & Revenue Contribution',          5, true),

  -- ── warehouse-picker (b000000f) — 4 modules ──────────────────────────────
  ('c0000043-0000-0000-0000-000000000000', 'b000000f-0000-0000-0000-000000000000', 'Warehouse Safety & Manual Handling', 1, true),
  ('c0000044-0000-0000-0000-000000000000', 'b000000f-0000-0000-0000-000000000000', 'Pick-and-Pack Workflows',            2, true),
  ('c0000045-0000-0000-0000-000000000000', 'b000000f-0000-0000-0000-000000000000', 'Inventory Accuracy & WMS Basics',    3, true),
  ('c0000046-0000-0000-0000-000000000000', 'b000000f-0000-0000-0000-000000000000', 'Dispatch Standards & Communication', 4, true)

ON CONFLICT (id) DO NOTHING;


-- =============================================================================
-- 5. PLACEHOLDER TOPICS for all new modules
--
-- Topic counts come directly from lib/roles.ts → each role's modules array.
-- Titles are "Topic N — [module title]" — enough to render in the UI.
-- content_body is a minimal text block so the topic reader doesn't crash.
-- The real content will be authored in Sanity and synced via the CMS layer.
--
-- This block is IDEMPOTENT: the WHERE NOT EXISTS guard prevents duplicates
-- on re-run, so the DO block can be executed safely multiple times.
-- =============================================================================

DO $$
DECLARE
  _module_ids   uuid[];
  _topic_counts int[];
  _mid          uuid;
  _tc           int;
  _i            int;
  _idx          int;
  _mod_title    text;
  _placeholder  jsonb;
BEGIN
  -- Pair every new module UUID with its topic count from lib/roles.ts
  -- Format: (module_uuid, topic_count)
  -- ── cashier-retail modules 3-5 ──────────────────────────────────────────
  _module_ids   := ARRAY[
    'c0000007-0000-0000-0000-000000000000'::uuid,  -- Cash Handling & Reconciliation (6)
    'c0000008-0000-0000-0000-000000000000'::uuid,  -- Store Policy & Loss Prevention (5)
    'c0000009-0000-0000-0000-000000000000'::uuid,  -- Shift Operations & Handover (6)
  -- ── waiter-waitress modules 3-5 ─────────────────────────────────────────
    'c000000a-0000-0000-0000-000000000000'::uuid,  -- Food Safety & Personal Hygiene (5)
    'c000000b-0000-0000-0000-000000000000'::uuid,  -- Guest Handling & Complaints (5)
    'c000000c-0000-0000-0000-000000000000'::uuid,  -- Shift Open & Close Procedures (5)
  -- ── dispatch-rider modules 3-4 ──────────────────────────────────────────
    'c000000d-0000-0000-0000-000000000000'::uuid,  -- Delivery SOPs & Documentation (5)
    'c000000e-0000-0000-0000-000000000000'::uuid,  -- Customer Interaction & Dispute Handling (5)
  -- ── store-attendant 4 modules ────────────────────────────────────────────
    'c000000f-0000-0000-0000-000000000000'::uuid,  -- Store Operations Overview (5)
    'c0000010-0000-0000-0000-000000000000'::uuid,  -- Stock Receiving & Inventory (6)
    'c0000011-0000-0000-0000-000000000000'::uuid,  -- Shelf Display & Merchandising (5)
    'c0000012-0000-0000-0000-000000000000'::uuid,  -- Customer Assistance & Sales (6)
  -- ── barista 5 modules ────────────────────────────────────────────────────
    'c0000013-0000-0000-0000-000000000000'::uuid,  -- Coffee Fundamentals & Bean Knowledge (5)
    'c0000014-0000-0000-0000-000000000000'::uuid,  -- Espresso Extraction Techniques (5)
    'c0000015-0000-0000-0000-000000000000'::uuid,  -- Milk Steaming & Latte Art Basics (5)
    'c0000016-0000-0000-0000-000000000000'::uuid,  -- Beverage Recipes & Menu Execution (5)
    'c0000017-0000-0000-0000-000000000000'::uuid,  -- Equipment Care & Hygiene Compliance (4)
  -- ── customer-service-rep 5 modules ───────────────────────────────────────
    'c0000018-0000-0000-0000-000000000000'::uuid,  -- Communication Skills (5)
    'c0000019-0000-0000-0000-000000000000'::uuid,  -- Handling Complaints (6)
    'c000001a-0000-0000-0000-000000000000'::uuid,  -- Product & Service Knowledge (5)
    'c000001b-0000-0000-0000-000000000000'::uuid,  -- CRM Tools & Documentation (5)
    'c000001c-0000-0000-0000-000000000000'::uuid,  -- Follow-up & Quality Standards (5)
  -- ── receptionist 5 modules ───────────────────────────────────────────────
    'c000001d-0000-0000-0000-000000000000'::uuid,  -- Front Desk & Visitor Management (5)
    'c000001e-0000-0000-0000-000000000000'::uuid,  -- Professional Communication (5)
    'c000001f-0000-0000-0000-000000000000'::uuid,  -- Scheduling & Calendar Management (5)
    'c0000020-0000-0000-0000-000000000000'::uuid,  -- Office Software Basics (5)
    'c0000021-0000-0000-0000-000000000000'::uuid,  -- Record Keeping (4)
  -- ── hairdresser 5 modules ─────────────────────────────────────────────────
    'c0000022-0000-0000-0000-000000000000'::uuid,  -- Salon Safety & Hygiene (5)
    'c0000023-0000-0000-0000-000000000000'::uuid,  -- Client Consultation (5)
    'c0000024-0000-0000-0000-000000000000'::uuid,  -- Cutting & Styling Techniques (6)
    'c0000025-0000-0000-0000-000000000000'::uuid,  -- Chemical Treatments (5)
    'c0000026-0000-0000-0000-000000000000'::uuid,  -- Product Knowledge & Client Retention (5)
  -- ── security-guard 4 modules ─────────────────────────────────────────────
    'c0000027-0000-0000-0000-000000000000'::uuid,  -- Roles & Legal Responsibilities (5)
    'c0000028-0000-0000-0000-000000000000'::uuid,  -- Access Control & Patrol (5)
    'c0000029-0000-0000-0000-000000000000'::uuid,  -- Incident Reporting (4)
    'c000002a-0000-0000-0000-000000000000'::uuid,  -- Emergency Response (4)
  -- ── cook-kitchen-hand 5 modules ──────────────────────────────────────────
    'c000002b-0000-0000-0000-000000000000'::uuid,  -- Food Safety HACCP (5)
    'c000002c-0000-0000-0000-000000000000'::uuid,  -- Basic Cooking & Prep (5)
    'c000002d-0000-0000-0000-000000000000'::uuid,  -- Equipment Operation & Safety (5)
    'c000002e-0000-0000-0000-000000000000'::uuid,  -- Portion Control & Recipe (4)
    'c000002f-0000-0000-0000-000000000000'::uuid,  -- Kitchen Teamwork (5)
  -- ── sales-rep 5 modules ──────────────────────────────────────────────────
    'c0000030-0000-0000-0000-000000000000'::uuid,  -- Sales Mindset & Prospecting (5)
    'c0000031-0000-0000-0000-000000000000'::uuid,  -- Building Rapport (5)
    'c0000032-0000-0000-0000-000000000000'::uuid,  -- Pitching & Presentation (5)
    'c0000033-0000-0000-0000-000000000000'::uuid,  -- Objection Handling (6)
    'c0000034-0000-0000-0000-000000000000'::uuid,  -- Closing & After-Sales (4)
  -- ── hotel-housekeeper 4 modules ──────────────────────────────────────────
    'c0000035-0000-0000-0000-000000000000'::uuid,  -- Housekeeping Standards (5)
    'c0000036-0000-0000-0000-000000000000'::uuid,  -- Room Turnover Procedures (5)
    'c0000037-0000-0000-0000-000000000000'::uuid,  -- Linen & Amenity Management (5)
    'c0000038-0000-0000-0000-000000000000'::uuid,  -- Chemical Safety (5)
  -- ── barber 5 modules ─────────────────────────────────────────────────────
    'c0000039-0000-0000-0000-000000000000'::uuid,  -- Hygiene & Tool Sterilisation (4)
    'c000003a-0000-0000-0000-000000000000'::uuid,  -- Client Consultation (4)
    'c000003b-0000-0000-0000-000000000000'::uuid,  -- Fade Techniques & Blending (6)
    'c000003c-0000-0000-0000-000000000000'::uuid,  -- Lineups, Trims & Beard (5)
    'c000003d-0000-0000-0000-000000000000'::uuid,  -- Shop Operations (3)
  -- ── front-desk-agent 5 modules ───────────────────────────────────────────
    'c000003e-0000-0000-0000-000000000000'::uuid,  -- Hotel Operations (5)
    'c000003f-0000-0000-0000-000000000000'::uuid,  -- Check-in & Reservations (5)
    'c0000040-0000-0000-0000-000000000000'::uuid,  -- PMS Basics (5)
    'c0000041-0000-0000-0000-000000000000'::uuid,  -- Guest Relations & Complaints (5)
    'c0000042-0000-0000-0000-000000000000'::uuid,  -- Upselling & Revenue (4)
  -- ── warehouse-picker 4 modules ───────────────────────────────────────────
    'c0000043-0000-0000-0000-000000000000'::uuid,  -- Warehouse Safety (5)
    'c0000044-0000-0000-0000-000000000000'::uuid,  -- Pick-and-Pack Workflows (5)
    'c0000045-0000-0000-0000-000000000000'::uuid,  -- Inventory Accuracy & WMS (4)
    'c0000046-0000-0000-0000-000000000000'::uuid   -- Dispatch Standards (4)
  ];

  _topic_counts := ARRAY[
  -- cashier modules 3-5
    6, 5, 6,
  -- waiter modules 3-5
    5, 5, 5,
  -- dispatch-rider modules 3-4
    5, 5,
  -- store-attendant
    5, 6, 5, 6,
  -- barista
    5, 5, 5, 5, 4,
  -- customer-service-rep
    5, 6, 5, 5, 5,
  -- receptionist
    5, 5, 5, 5, 4,
  -- hairdresser
    5, 5, 6, 5, 5,
  -- security-guard
    5, 5, 4, 4,
  -- cook-kitchen-hand
    5, 5, 5, 4, 5,
  -- sales-rep
    5, 5, 5, 6, 4,
  -- hotel-housekeeper
    5, 5, 5, 5,
  -- barber
    4, 4, 6, 5, 3,
  -- front-desk-agent
    5, 5, 5, 5, 4,
  -- warehouse-picker
    5, 5, 4, 4
  ];

  -- Placeholder content_body — minimal but valid for the topic reader
  _placeholder := '{"sections": [{"heading": "Overview", "body": "This topic is being prepared. Full content will be available soon."}], "estimated_read_minutes": 10}'::jsonb;

  FOR _idx IN 1..array_length(_module_ids, 1) LOOP
    _mid := _module_ids[_idx];
    _tc  := _topic_counts[_idx];

    -- Fetch module title for descriptive topic names
    SELECT title INTO _mod_title FROM modules WHERE id = _mid;

    FOR _i IN 1.._tc LOOP
      INSERT INTO topics (module_id, title, content_type, order_index, estimated_minutes, is_published, content_body)
      SELECT
        _mid,
        'Part ' || _i || ': ' || _mod_title,
        'text',
        _i,
        10,
        true,
        _placeholder
      WHERE NOT EXISTS (
        SELECT 1 FROM topics WHERE module_id = _mid AND order_index = _i
      );
    END LOOP;
  END LOOP;
END;
$$;


-- =============================================================================
-- 6. PLACEHOLDER TOPICS for existing modules that 004_seed.sql left empty
--    (modules c0000001-c0000006 had 3 topics each in 004_seed but the DO block
--     above skips them — they're handled by 004_seed.sql already)
-- =============================================================================
-- Nothing to do here — 004_seed.sql inserted topics d0000001-d0000012 for
-- modules c0000001-c0000006. The WHERE NOT EXISTS guard above would skip
-- those even if we included them, so no action needed.


-- =============================================================================
-- 7. ROLE PROGRESSIONS  (career path graph — next + adjacent edges)
-- =============================================================================

INSERT INTO role_progressions (from_role_id, to_role_id, progression_type, display_order)
VALUES
  -- Retail path: cashier → store-attendant (natural next)
  ('b0000001-0000-0000-0000-000000000000', 'b0000004-0000-0000-0000-000000000000', 'next', 1),
  -- Retail path: cashier → sales-rep (adjacent stretch)
  ('b0000001-0000-0000-0000-000000000000', 'b000000b-0000-0000-0000-000000000000', 'adjacent', 2),

  -- F&B path: waiter → cook (adjacent)
  ('b0000002-0000-0000-0000-000000000000', 'b000000a-0000-0000-0000-000000000000', 'adjacent', 1),
  -- F&B path: waiter → barista (adjacent)
  ('b0000002-0000-0000-0000-000000000000', 'b0000005-0000-0000-0000-000000000000', 'adjacent', 2),
  -- F&B path: waiter → front-desk-agent (next — hospitality growth)
  ('b0000002-0000-0000-0000-000000000000', 'b000000e-0000-0000-0000-000000000000', 'next', 3),

  -- Logistics: dispatch-rider → warehouse-picker (adjacent)
  ('b0000003-0000-0000-0000-000000000000', 'b000000f-0000-0000-0000-000000000000', 'adjacent', 1),

  -- Hospitality: hotel-housekeeper → front-desk-agent (next)
  ('b000000c-0000-0000-0000-000000000000', 'b000000e-0000-0000-0000-000000000000', 'next', 1),

  -- Beauty: barber → hairdresser (adjacent — expand service range)
  ('b000000d-0000-0000-0000-000000000000', 'b0000008-0000-0000-0000-000000000000', 'adjacent', 1),

  -- Admin: receptionist → customer-service-rep (next)
  ('b0000007-0000-0000-0000-000000000000', 'b0000006-0000-0000-0000-000000000000', 'next', 1),
  -- Admin: security-guard → receptionist (adjacent)
  ('b0000009-0000-0000-0000-000000000000', 'b0000007-0000-0000-0000-000000000000', 'adjacent', 1),

  -- Sales: customer-service-rep → sales-rep (next)
  ('b0000006-0000-0000-0000-000000000000', 'b000000b-0000-0000-0000-000000000000', 'next', 1)

ON CONFLICT (from_role_id, to_role_id) DO NOTHING;


-- =============================================================================
-- 8. ADDITIONAL BADGES  (supplement the starter set in 004_seed.sql)
-- =============================================================================

INSERT INTO badges (id, slug, name, description, trigger_type, trigger_value)
VALUES
  ('f0000007-0000-0000-0000-000000000000',
   'three-roles', 'Hat Trick', 'Enrolled in 3 different roles',
   'roles_enrolled', '{"count": 3}'),

  ('f0000008-0000-0000-0000-000000000000',
   'seven-day-streak', 'On a Roll', 'Maintained a 7-day learning streak',
   'streak_days', '{"days": 7}'),

  ('f0000009-0000-0000-0000-000000000000',
   'five-modules', 'Module Master', 'Passed 5 module tests',
   'module_completed', '{"count": 5}'),

  ('f000000a-0000-0000-0000-000000000000',
   'three-certs', 'Triple Certified', 'Earned 3 certificates',
   'certificate_issued', '{"count": 3}')

ON CONFLICT (id) DO NOTHING;
